import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './index.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Apzinho toddys',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="ptbr">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
